_wandb:
    value:
        cli_version: 0.25.0
        e:
            n3cwe5wcg5hljzbdilgy804odtqn5cg6:
                codePath: /home/crimson/Projects/Acads/DL/A1/da6401_assignment_1/notebooks/wandb_demo.ipynb
                codePathLocal: wandb_demo.ipynb
                email: ee23b055@smail.iitm.ac.in
                executable: /home/crimson/Projects/Acads/DL/A1/.venv/bin/python
                host: tuxedo-os
                os: Linux-6.14.0-116036-tuxedo-x86_64-with-glibc2.39
                program: /home/crimson/Projects/Acads/DL/A1/da6401_assignment_1/notebooks/wandb_demo.ipynb
                python: CPython 3.12.3
                root: /home/crimson/Projects/Acads/DL/A1/da6401_assignment_1/notebooks
                startedAt: "2026-02-20T14:19:50.436617Z"
                writerId: n3cwe5wcg5hljzbdilgy804odtqn5cg6
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.12.3
            "5": 0.25.0
            "8":
                - 1
                - 2
            "12": 0.25.0
            "13": linux-x86_64
epochs:
    value: 50
learning_rate:
    value: 0.01
loss_type:
    value: mae
weight_init:
    value: random
